* The Group Project 
In teams of 3-5 students, carry out a pilot experiment that measures a causal effect of interest.

- The experiment should involve at least 30 observations per treatment.  Please note, that when you perform your power calculations, that for an experiment with 30 observations to be run, you should have both (a) a /strong/ treatment effect, and (b) a /very/ clean measurement of your outcome.
- The data may be collected either online or offline.  If the latter, students may choose to divide up the data collection, but be careful to balance the data collection across potentially heterogeneous clusters in different locations.

* Project Aims 
- Our intentions for this project is for you to learn what it is like to do an experiment in practice. This means identifying the theory that you want to test, deducing hypotheses that would support that theory, developing a measurement scheme for your outcomes, and then designing and executing an experiment that will systematically reveal subjects' potential outcome.
- We understand that, given the limited scope of the project, it may not be possible for you to have the perfect design or enough observations that your data will be academically publishable.
- It is /critically/ important to run a pilot experiment with a small number of observations. This will help you debug problems in execution before going ahead to collect all your data. 
- We strongly encourage you to collect real field experimental data instead of survey data. However, collecting data via a survey is common given the time constraints of a semester. If you do so, a common solution is to use Qualtrics, to which Berkeley has a license. Register for a free account using your Berkeley login at berkeley.qualtrics.com. Then, [[http://brentcurdy.net/qualtrics-tutorials/link/][this]] tutorial has good instructions on recruiting subjects to your survey using Mechanical Turk.

* Presentation
- During one of the final classes, we will ask you to present your findings to your peers for feedback that might help you improve your final paper. Please don’t spend time making the presentation pretty; this will not get an explicit grade.
- See the document `/finalProject/presentationGuidelines.pdf` for more information about these presentations. 

* The Final Paper 
- See the document `/finalProject/projectGuidelines.org` for the most detailed information about what to complete for the project. 

* Reimbursements
- See the document `/finalProject/reimbursements.org` for how to submit reimbursements for the project. Upon approval by an instructor, each group has as much as $500 to spend on experiment supplies. 
