* Reimbursements Process for MIDS 

Each project group, with the approval of the instructor, can spend up to $500 to purchase experiment materials. This might include the copies to make paper copies of surveys, the cost of shipping if you were providing free shipping to subjects to see if this induced increased purchases, AWS server space, or wages for subject's time. Before you spend this money, /please/ talk with the instructor to ensure that your spending can be defended to the I School front office. We won't let you be left holding the bag for a charge -- but that means that we instructors are internalizing the risk! 

When it comes time to complete the reimbursements proces, do the following: 
- Complete the following [[https://docs.google.com/forms/d/e/1FAIpQLSfH0QO5mmPhMMM2KYncJJ4BE_ZtrCZvVmeftO3E621yL1Q4qA/viewform?usp=sf_link][form]], which we will use to batch the reimbursement. 

* Things to be aware of
- If people have unique or complicated tax, fellowship, or financial support situations, the vessel that we have to use to reimburse you -- a research fellowship in the amount of the project expense -- might make your taxes, fellowship or financial support more complicated.
- If you live abroad, things will /certainly/ be more complicated. 
- If you're graduating the semester that you take 241, things may be more complicated. 
- So, in general, if someone who does not have these complexities would like to pre-spend, you can reduce the complexity of this process. 
